import { AppState } from './types';

export const INITIAL_STATE: AppState = {
  profile: {
    name: '',
    location: '',
    temperature: '',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200&h=200',
    avatarSleepUrl: '',
    avatarFitnessUrl: '',
    avatarWeightUrl: '' as any,
    avatarNutritionUrl: '',
    streakDays: 0,
  },
  waterIntakeCups: 0,
  waterIntakeGoalCups: 8,
  currentWeight: 0,
  weightGoal: 0,
  weightViewMode: 'weekly',
  weightLogs: [],
  meals: [],
  workouts: [],
  sleepScore: 0,
  sleepGoalHours: 8.0,
  bedTime: '22:30',
  wakeTime: '06:30',
  sleepLogs: [],
  dailyProgressPercentage: 0,
  ringCalories: 0,
  ringCaloriesGoal: 600,
  ringMinutes: 0,
  ringMinutesGoal: 30,
  ringStand: 0,
  ringStandGoal: 12,
  agendaEvents: [],
  courses: [],
  books: [],
  recentActivities: [],
  notificationsEnabled: false,
  biometricsEnabled: false,
  contacts: []
};

export const getCleanInitialState = (name: string): AppState => ({
  profile: {
    name: name === 'Usuário' ? '' : name,
    location: '',
    temperature: '',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200&h=200',
    avatarSleepUrl: '',
    avatarFitnessUrl: '',
    avatarWeightUrl: '',
    avatarNutritionUrl: '',
    streakDays: 0,
  },
  waterIntakeCups: 0,
  waterIntakeGoalCups: 8,
  currentWeight: 75.0,
  weightGoal: 70.0,
  weightLogs: [],
  weightViewMode: 'weekly',
  meals: [],
  workouts: [],
  sleepScore: 0,
  sleepGoalHours: 8.0,
  bedTime: '22:30',
  wakeTime: '06:30',
  sleepLogs: [],
  dailyProgressPercentage: 0,
  ringCalories: 0,
  ringCaloriesGoal: 600,
  ringMinutes: 0,
  ringMinutesGoal: 30,
  ringStand: 0,
  ringStandGoal: 12,
  agendaEvents: [],
  courses: [],
  books: [],
  recentActivities: [],
  notificationsEnabled: false,
  biometricsEnabled: false,
  contacts: []
});
