import { AppState } from './types';

export const INITIAL_STATE: AppState = {
  profile: {
    name: '',
    location: '',
    temperature: '',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200&h=200',
    avatarSleepUrl: '',
    avatarFitnessUrl: '',
    avatarWeightUrl: '' as any,
    avatarNutritionUrl: '',
    streakDays: 0,
    height: 175,
  },
  waterIntakeCups: 0,
  waterIntakeGoalCups: 8,
  currentWeight: 0,
  weightGoal: 0,
  weightViewMode: 'weekly',
  weightLogs: [],
  meals: [],
  workouts: [],
  sleepScore: 0,
  sleepGoalHours: 8.0,
  bedTime: '22:30',
  wakeTime: '06:30',
  sleepLogs: [],
  dailyProgressPercentage: 0,
  ringCalories: 0,
  ringCaloriesGoal: 600,
  ringMinutes: 0,
  ringMinutesGoal: 30,
  ringStand: 0,
  ringStandGoal: 12,
  agendaEvents: [],
  courses: [],
  books: [],
  recentActivities: [],
  notificationsEnabled: false,
  biometricsEnabled: false,
  locationEnabled: false,
  contacts: [],
  notifications: [
    {
      id: 'notif-1',
      category: 'vyn',
      source: 'VYN AI INSIGHT',
      time: 'Agora',
      title: 'Janela de Foco Otimizada',
      description: 'Sua noite de sono atingiu ótima qualidade. Vyn AI calculou que sua janela de foco cognitivo ideal hoje será às 09:00.',
      read: false,
    },
    {
      id: 'notif-2',
      category: 'saude',
      source: 'LEMBRETE DE SAÚDE',
      time: '15m atrás',
      title: 'Beber Água',
      description: 'Mantenha-se hidratado! Hora de beber mais um copo (250ml) de água para atingir sua meta.',
      read: false,
      actionType: 'water',
      actionLabel: 'Registrar Copo',
    },
    {
      id: 'notif-3',
      category: 'produtividade',
      source: 'PRODUTIVIDADE',
      time: '45m atrás',
      title: 'Reunião de Design',
      description: 'Sua reunião de alinhamento está agendada para começar em breve. Prepare seu material!',
      read: false,
      actionType: 'meet',
      actionLabel: 'Join Meet',
      metaData: { link: 'https://meet.google.com/vyn-tra-meet' }
    },
    {
      id: 'notif-4',
      category: 'conquista',
      source: 'CONQUISTA',
      time: '2h atrás',
      title: 'Consistência Imbatível!',
      description: 'Parabéns! Você está com uma sequência ativa de dias saudáveis e focados registrados no Vyntra.',
      read: true,
    }
  ]
};

export const getCleanInitialState = (name: string): AppState => ({
  profile: {
    name: name === 'Usuário' ? '' : name,
    location: '',
    temperature: '',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200&h=200',
    avatarSleepUrl: '',
    avatarFitnessUrl: '',
    avatarWeightUrl: '',
    avatarNutritionUrl: '',
    streakDays: 0,
    height: 175,
    birthDate: '',
  },
  waterIntakeCups: 0,
  waterIntakeGoalCups: 8,
  currentWeight: 75.0,
  weightGoal: 70.0,
  weightLogs: [],
  weightViewMode: 'weekly',
  meals: [],
  workouts: [],
  sleepScore: 0,
  sleepGoalHours: 8.0,
  bedTime: '22:30',
  wakeTime: '06:30',
  sleepLogs: [],
  dailyProgressPercentage: 0,
  ringCalories: 0,
  ringCaloriesGoal: 600,
  ringMinutes: 0,
  ringMinutesGoal: 30,
  ringStand: 0,
  ringStandGoal: 12,
  agendaEvents: [],
  courses: [],
  books: [],
  recentActivities: [],
  notificationsEnabled: false,
  biometricsEnabled: false,
  locationEnabled: false,
  contacts: [],
  notifications: [
    {
      id: 'notif-1',
      category: 'vyn',
      source: 'VYN AI INSIGHT',
      time: 'Agora',
      title: 'Janela de Foco Otimizada',
      description: 'Sua noite de sono atingiu ótima qualidade. Vyn AI calculou que sua janela de foco cognitivo ideal hoje será às 09:00.',
      read: false,
    },
    {
      id: 'notif-2',
      category: 'saude',
      source: 'LEMBRETE DE SAÚDE',
      time: '15m atrás',
      title: 'Beber Água',
      description: 'Mantenha-se hidratado! Hora de beber mais um copo (250ml) de água para atingir sua meta.',
      read: false,
      actionType: 'water',
      actionLabel: 'Registrar Copo',
    },
    {
      id: 'notif-3',
      category: 'produtividade',
      source: 'PRODUTIVIDADE',
      time: '45m atrás',
      title: 'Reunião de Design',
      description: 'Sua reunião de alinhamento está agendada para começar em breve. Prepare seu material!',
      read: false,
      actionType: 'meet',
      actionLabel: 'Join Meet',
      metaData: { link: 'https://meet.google.com/vyn-tra-meet' }
    },
    {
      id: 'notif-4',
      category: 'conquista',
      source: 'CONQUISTA',
      time: '2h atrás',
      title: 'Consistência Imbatível!',
      description: 'Parabéns! Você está com uma sequência ativa de dias saudáveis e focados registrados no Vyntra.',
      read: true,
    }
  ]
});
